/* package codechef; // don't place package name! */

import java.util.Scanner;

/* Name of the class has to be "Main" only if the class is public. */
class Codechef
{
	public static void main (String[] args) throws java.lang.Exception
	{
		// your code goes here
		Scanner in = new Scanner(System.in);
		int T = in.nextInt(); //for No. of test cases
		while(T-->0) {
		    //your code goes here
		    int a = in.nextInt(); //Units of power required per year
		    int b = in.nextInt(); //No. of years
		    int x = in.nextInt(); //Amount of Helium-3 in grams
		    int y = in.nextInt(); //units of power generated by Helium-3 per gram
		    System.out.println(x*y<a*b?"No":"Yes");
		}
		in.close();
	}
}
